### ISSUE TITLE
update aws-scala-tools dependency

### ISSUE THREAD

**Issue by marina-manrique** [ohnosequences/aws-statika#11]
This causes conflicts as I need 0.14.x elsewhere. Probably we should release 0.14.0 before?

**Comment by laughedelic** [comment]
which conflicts? AFAIK, everything depends now on `0.13.2`, isn't it?

**Comment by marina-manrique** [comment]
But the new instance types names, `m3.x2large` for example, are supported in `0.14.x` not `0.13.2`

**Comment by laughedelic** [comment]
yes, it will be in the next release. but I would like to resolve https://github.com/ohnosequences/aws-scala-tools/pull/23 before releasing `0.14.0`. Instance type names are not a big deal, we can change it later.

**Comment by marina-manrique** [comment]
:+1:

**Comment by laughedelic** [comment]
Done. Closing.
